name: ECR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::927485958639:role/deploy-role-056ee03
          role-session-name: deploy-role-session
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Docker image
        run: docker build --tag test-frontend:v1.0.0 .
      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          region: eu-central-1
          local-image: test-frontend:v1.0.0
          image: 927485958639.dkr.ecr.eu-central-1.amazonaws.com/test-frontend-170db36:v1.0.0
